### ISSUE TITLE
Data returned from Library is not usable

### ISSUE THREAD

**Issue by marcousa** [gionoa/Formula1API#39]
Hello,

First of all, thank you for putting this together!
I added it to my project using Swift Package Manager and was able to use it to make calls to the Ergast API and print the resulting objects.

The problem is that the only object that is returned is the top-level one, and nothing else is accessible.
For example if I tried to get Circuit info for 2021, my code would be:

`Formula1API.circuits(for: .year(2021)) 
{  result in
    switch result {
        case .success(let circuits):
            print(circuits)
        case .failure(let error):
            print(error)
    }
}`

This works...BUT the "circuits" object can't be accessed (for example, I can't reach its "data" property because it is set to "internal" access-level only).

Unless I'm missing a step, this means I can't unpack the Circuits to get to an individual Circuit (or use the object in any other way).

I'd appreciate any help or guidance you can provide.

Thank you,

Marco

**Comment by gionoa** [comment]
Hi Marco! Thanks for checking it out, my pleasure! 

I actually ran into this while working with it recently myself... I'll address this and get it fixed soon 👍🏽

**Comment by gionoa** [comment]
As it turns out, [this](https://github.com/gionoa/Formula1API/commit/4827d22866c8538863cac13f3f23c91884275067) commit   provides public access to the `Circuits` endpoint structs. I'll refer this ticket when I open a PR for the rest

**Comment by gionoa** [comment]
Thanks for your patience @marcousa! So here's an example that fetches all circuits, with a list of 5 per page : 

```swift
class CircuitsProvider: ObservableObject {
    @Published var circuits: [Circuit] = .init()
    private let limit = "5"
    
    func fetchCircuits() {
        Formula1API.circuits(for: .all, limit: limit) { result in
            switch result {
            case let .success(response):
                self.circuits = response.data.circuitTable.circuits
            case let .failure(error):
                print("error")
            }
        }
    }
    
    func item(at index: Int) -> String {
        guard index < circuits.count else { return "" }
        return circuits[index].circuitName
    }
    
    init() {
       fetchCircuits()
    }
}
